# Generated by Django 3.1.4 on 2021-01-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_images',
            field=models.ImageField(null=True, upload_to='drivers/'),
        ),
    ]
